"""Constants for core physics and biochem models."""

# --- Pushforward & Biochem Scaling Constants ---
DEFAULT_DELTA_VALUE_SCALE = 150000.0
DEFAULT_SATURATION_SCALE = 80.0
DEFAULT_DELTA_THRESH = 5e-6
DEFAULT_STATE_SCALE = 0.002
DEFAULT_MAX_SAT_LOG = 0.002

# --- Time & Scheduling ---
DEFAULT_TIME_REF_S = 3000.0
DEFAULT_TAU_CENTER = 25.0
DEFAULT_TAU_SIGMA = 6.0

# --- Loss Defaults ---
DEFAULT_HUBER_BETA_GROWTH = 0.5
DEFAULT_HUBER_BETA_FULL = 1e-4
DEFAULT_LOSS_SCALE_GROWTH = 1.0
DEFAULT_LOSS_SCALE_FULL = 10000.0
