"""Canonical deployable biochem stack (hybrid SciML pipeline).

Historical import path ``src.biochem_gnn``; prefer ``from src.biochem_deploy import …`` (thin alias).
Stack id: ``biochem_deploy`` (legacy: biochem_gnn, clot_deploy_gnn).
SciML taxonomy: ``docs/MODEL_NOMENCLATURE.md``.
"""

from src.biochem_gnn.config import (
    BETA_CKPT,
    COMPONENT_CLOT,
    COMPONENT_CLOT_TRIGGER_PHYSICS,
    COMPONENT_FLOW,
    COMPONENT_FLOW_COUPLING,
    COMPONENT_GELATION_BETA,
    COMPONENT_GINO_DEQ_KINE,
    COMPONENT_PMGP_DEQ_KINE,
    COMPONENT_SPECIES,
    COMPONENT_SPECIES_GNN,
    COMPONENT_VISCOSITY,
    DEPLOY_HORIZON_DEFAULT,
    DEPLOY_MAX_UNROLL_CAP,
    LEGACY_CAPPED_DEPLOY_HORIZON,
    GLOBAL_CKPT,
    LOAO_DIR,
    LOCKED_DIR,
    PHASE_CKPT,
    PHASE_TRAIN,
    STACK_NAME,
    VAL_ANCHOR_DEFAULT,
    apply_deploy_env,
    apply_train_recipe_env,
    beta_ckpt_path,
    global_ckpt_path,
    is_biochem_gnn_checkpoint_phase,
    is_deploy_gnn_checkpoint_phase,
    load_manifest,
    loao_root_path,
    locked_root_path,
    normalize_train_phase,
    reference_manifest_path,
    species_ckpt_for_anchor,
)
from src.biochem_gnn.model import (
    MODELED_SPECIES_NAMES,
    N_MODELED_SPECIES,
    BiochemDeployConfig,
    BiochemDeployRollout,
    BiochemDeployStack,
    BiochemGNN,
    BiochemGNNConfig,
    BiochemGNNRollout,
    FlowMode,
)

__all__ = [
    "STACK_NAME",
    "PHASE_TRAIN",
    "PHASE_CKPT",
    "VAL_ANCHOR_DEFAULT",
    "DEPLOY_HORIZON_DEFAULT",
    "DEPLOY_MAX_UNROLL_CAP",
    "LEGACY_CAPPED_DEPLOY_HORIZON",
    "GLOBAL_CKPT",
    "BETA_CKPT",
    "LOAO_DIR",
    "LOCKED_DIR",
    "COMPONENT_SPECIES_GNN",
    "COMPONENT_GELATION_BETA",
    "COMPONENT_CLOT_TRIGGER_PHYSICS",
    "COMPONENT_PMGP_DEQ_KINE",
    "COMPONENT_GINO_DEQ_KINE",
    "COMPONENT_FLOW_COUPLING",
    "COMPONENT_SPECIES",
    "COMPONENT_VISCOSITY",
    "COMPONENT_CLOT",
    "COMPONENT_FLOW",
    "apply_train_recipe_env",
    "apply_deploy_env",
    "load_manifest",
    "global_ckpt_path",
    "beta_ckpt_path",
    "loao_root_path",
    "locked_root_path",
    "reference_manifest_path",
    "species_ckpt_for_anchor",
    "normalize_train_phase",
    "is_biochem_gnn_checkpoint_phase",
    "is_deploy_gnn_checkpoint_phase",
    "BiochemDeployStack",
    "BiochemDeployConfig",
    "BiochemDeployRollout",
    "BiochemGNN",
    "BiochemGNNConfig",
    "BiochemGNNRollout",
    "FlowMode",
    "N_MODELED_SPECIES",
    "MODELED_SPECIES_NAMES",
]
